WORD_LIST = [
    "Knight", "吃烧烤", "Coffee", "Magic", "早上好啊！", "Neon", "Stone", "Water",
    "Dragon", "打麻将", "Tea", "Dream", "晚安zzz~", "Pixel", "Fire", "Wind",
    "Wizard", "撸猫", "Latte", "Chaos", "加油！", "Glitch", "Ice", "Cloud",
    "Samurai", "嗦粉", "Mocha", "Time", "哈哈哈", "Cyber", "Lava", "Rain",
    "Phoenix", "追剧", "Matcha", "Void", "冲鸭～", "Hologram", "Sand", "Fog",
    "Ninja", "逛夜市", "Espresso", "Echo", "稳了！", "Quantum", "Ash", "Dew",
    "Sorcerer", "贴秋膘", "Cappuccino", "Myth", "绝了！", "Synth", "Mist", "Wave",
    "Alchemist", "嗑瓜子", "Americano", "BBQ", "Future","雨骤风急", "Static hum", "煎饼摊前排长队", "Nebula drifts", "等等，好像不对……",
    "竹影扫阶尘不动", "Kernel panic", "螺蛳粉配冰啤酒", "Echo in the canyon",
    "老板，打包一份人间烟火", "Flicker—then gone", "地铁门关闭的瞬间", "Solstice night",
    "薯片袋里最后一片", "Oops, recursion detected", "猫跳上键盘的那一刻", "Dew on spiderweb",
    "泡面升腾的热气", "……后来，风停了", "Quantum leap", "追公交失败实录",
    "桂花香穿窗而入", "404: Motivation not found", "番茄炒蛋的哲学", "Whispered oath",
    "凌晨四点的键盘声", "Wait—did that just happen?", "Ash after bonfire", "冰箱空荡荡",
    "骑单车冲下坡的自由", "Fragmented memory", "老板说‘再改一版’", "Dust motes in sunlight",
    "蹲守打折酸奶", "System overload: joy", "外婆说‘趁热吃’", "Silent thunder",
    "Wi-Fi信号满格但心很空", "Fractured light", "火候刚好", "Pause… breathe… continue.",
    "秋裤穿还是不穿", "Latent variable", "锅气十足", "The silence between notes",
    "文件未保存，断电", "Frozen moment", "糖醋排骨微焦边", "Reality glitch",
    "图书馆角落的哈欠", "Unspoken understanding", "雨停了，云还在走", "Zero-point energy","追风", "Dusk", "吃宵夜", "Static", "别慌", "Glow",  
    "雨停了", "Oops", "糖炒栗", "Frost", "稳住", "Zen",  
    "翻车了", "Hush", "煮咖啡", "Ashes", "摸鱼", "Drift",  
    "晚来风", "Whoa", "烤红薯", "Mist", "卡壳", "Blink",  
    "听雨声", "Echo", "等公交", "Void", "困了", "Fume",  
    "吹晚风", "Haze", "泡茶去", "Rust", "跑偏", "Shhh",  
    "烟火气", "Wisp", "翻旧照", "Dust", "走神", "Fray",  
    "落日熔", "Gale", "烫手山芋", "Lull", "卡顿", "Snap",  
    "猫伸腰", "Hiss", "云游", "Murmur", "失联", "Tilt",  
    "锅开了", "Hollow", "溜达", "Frost", "断片", "Wane", "Vortex", "晚风轻拂", "Starship", "吃一碗热汤", "Whispers...", "朝霞", "Mystic Dreams", "温暖的笑容",
    "Cyberpunk", "城市的夜晚", "Volcano!", "空灵之音", "Sunrise", "冰雪", "Shadowfall", "迷人的笑容",
    "Neon Lights", "让我们去海边", "Sparks Fly", "月亮的思念", "Zen Garden", "夜晚的星辰", "Hologram", "黑夜漫步",
    "Quantum Leap", "从容而立", "Rose Petals", "火烈鸟", "Moonlight Serenade", "呼吸大自然", "Cosmos", "鸟语花香",
    "Echoes of Time", "用心感受", "Pine Tree", "咖啡的香气", "Lunar Eclipse", "渔火", "Waves Crash", "海风拂面",
    "Solitude", "不负春光", "Electric Dreams", "下午茶时光", "Dancing Lights", "悠然自得", "Rising Sun", "清晨的微光",
    "Starlight", "青春年华", "Mystery Garden", "迷失在森林", "Skyline", "人海浮沉", "Autumn Leaves", "风铃的声音",
    "Phoenix Rising", "月光下的舞者", "Golden Sands", "自由翱翔", "Dreamcatcher", "湖面倒影", "Whirlwind", "静谧的湖泊",
    "Shimmering Lights", "晚餐的味道", "Moonlit Path", "一抹微笑", "Tidal Wave", "岁月静好", "Crimson Sky", "追逐梦想",
    "Cappuccino Magic", "未曾相遇", "Time Flies", "星辰大海", "Burning Passion", "心如止水", "Silent Forest", "共赴山海",
    "Rainbow Bridge", "孤独的旅行者", "Shining Horizon", "星空下的誓言", "Twilight Dreams", "望着远方", "Golden Hour", "梦的彼岸"
]


# === 指令模板库 ===
INSTRUCTION_TEMPLATES = [
    'Change the text style of "{word}" to match the reference image.',
    'Apply the reference style to the word "{word}".',
    'Make the text "{word}" look like the style in the reference image.',
    'Change the style of the text "{word}" in the first image to match the style of the second image.',
    'Take the text "{word}" from image 1 and apply the visual style from image 2.',
    'Using the second image as a style reference, transform the appearance of the text "{word}" in the first image.',
    'Change the style of the text "{word}" to the style of the second image, keeping the text content unchanged.',
    'Keep the text content "{word}" from the first image, but render it using the style of the second image.',
    'Apply the style from image 2 to the text "{word}" shown in image 1.',
    'Render the text "{word}" from the first input image using the visual characteristics defined in the second image.',
    '把"{word}"的样式改成参考图的样子。',
    '把文字"{word}"的样式改成第二张图的样式,保持文字内容不变。',
    '让"{word}"具有和参考图一样的视觉风格。',
    '使用第二张图的风格来渲染第一张图中的文字"{word}"。',
    '将第一张图中的文字"{word}"应用第二张图的风格进行转换。',
    '参考第二张图的风格，改变第一张图中文字"{word}"的外观。',
    '保持第一张图中文字"{word}"的内容不变，但使用第二张图的风格进行渲染。',
    '将第二张图的风格应用到第一张图中的文字"{word}"上。',
    '把"{word}"变成参考图里展示的那种风格。',
    '把"{word}"变成第二张图里展示的那种风格。',
]